package com.chentiming.entity;
// Generated 2016-1-26 16:06:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Power generated by hbm2java
 */
@Entity
@Table(name = "power", catalog = "coin")
public class Power implements java.io.Serializable {

	private int id;
	private Integer num;

	public Power() {
	}

	public Power(int id) {
		this.id = id;
	}

	public Power(int id, Integer num) {
		this.id = id;
		this.num = num;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "num")
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

}
