package com.chentiming.entity;
// Generated 2016-1-26 16:06:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Skills generated by hbm2java
 */
@Entity
@Table(name = "skills", catalog = "coin")
public class Skills implements java.io.Serializable {

	private String id;
	private int level;
	private String name;

	public Skills() {
	}

	public Skills(String id, int level) {
		this.id = id;
		this.level = level;
	}

	public Skills(String id, int level, String name) {
		this.id = id;
		this.level = level;
		this.name = name;
	}

	@Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
